<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit46a15872d7a33d88eac240479dab0f41
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'chriskacerguis\\RestServer\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'chriskacerguis\\RestServer\\' => 
        array (
            0 => __DIR__ . '/..' . '/chriskacerguis/codeigniter-restserver/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit46a15872d7a33d88eac240479dab0f41::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit46a15872d7a33d88eac240479dab0f41::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
